spring.application.name=your-project-name

spring.datasource.url=jdbc:postgresql://localhost:5432/your-db-name
spring.datasource.username=your-db-username
spring.datasource.password=your-db-password

spring.jpa.hibernate.ddl-auto=create-drop or update

spring.jpa.show-sql=true

app.jwt.secret=your-jwt-secret
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000
app.jwt.access-cookie-name=accessToken
app.jwt.refresh-cookie-name=refreshToken

cors.allowed-origins=http://localhost:3000,http://localhost:4200